# 对接入了DeepSeek的应用进行分类
# 这些是应用的标签
# 每个应用只有一个标签
sort = ["实用工具", "系统应用", "效率办公", "金融理财", "摄影摄像", "学习教育", "影音视听", "居家生活", "聊天社交", "医疗健康", "新闻资讯", "旅游交通", "娱乐消遣", "图书阅读", "手机游戏", "时尚购物", "体育运动", "其他"]

# 以下就是接入了DeepSeek的应用汇总了
# 友友们在这里添加或修改你们知道的接入了DeepSeek的应用
#
# 模板长这样
# [应用包名]
# name = 应用名字
# type = 应用分类（填sort的内容）
# comment = 应用的备注（比如接在哪里，对应用的评价）

["com.deepseek.chat"]
name = "DeepSeek"
type = "实用工具"
comment = "DeepSeek的官方APP，不用我多说了吧"

["com.tencent.mm"]
name = "微信"
type = "聊天社交"
comment = "内测用户可以在搜索栏中调用DeepSeek进行搜索，其他用户会被调用到腾讯元宝上（TX常见行为）"

["com.miui.voiceassist"]
name = "小爱同学"
type = "系统应用"
comment = "对小爱同学说“打开深度思考”就可以用了"

["com.tencent.huanyuan.app.chat"]
name = "腾讯元宝"
type = "实用工具"
comment = "本职是做焕元大模型的，你知道的TX喜欢哪个火做哪个"

["com.qihoo.namiso"]
name = "纳米搜索"
type = "实用工具"
comment = "周红衣教主做的DeepSeek镜像，但是非常坑人，主打从DeepSeek那儿吸血，还吸用户的血"

["com.baidu.searchbox"]
name = "百度APP"
type = "实用工具"
comment = "百度嘛，你知道的，哪个火做哪个，对了莆田医院也接入了DeepSeek哦！"

["com.yuanshi.wenxiaobai"]
name = "问小白"
type = "实用工具"
comment = "本质是做AI搜索，和秘塔一样，不过没它火"

["com.kuaiduizuoye.scan"]
name = "快对"
type = "学习教育"
comment = "一个拍题软件怎么搞的全力DeepSeek进发，有点本末倒置了哈"

["com.zmzx.college.search"]
name = "大学搜题酱"
type = "学习教育"
comment = "一个拍题软件怎么搞的全力DeepSeek进发，有点本末倒置了哈"

["app.shadiao.jingluo"]
name = "鲸落文案"
type = "效率办公"
comment = "一个小而美的DeepSeek应用"